---
- name: remove services from managed hosts 
  hosts: myservers
  become: true
  tasks:
    - name: remove packages
      yum:
        name:
          - httpd
          - haproxy
          - firewalld
        state: absent
...        
