---
- name: try firewall rule
  hosts: servera.lab.example.com
  gather_facts: false
  become: true
  tasks:
    - name: try setting a firewall rule
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true

