---
- name: try forks
  hosts: all
  serial: 2
  order: sorted
  tasks:
    - name: task 1 sleep for 1 second
      command: sleep 1
      changed_when: false

    - name: task 2 sleep for 1 second
      command: sleep 1
      changed_when: false
...
