---
- name: try forks
  hosts: all
  max_fail_percentage: 1%
  serial:
    - 1
    - 50%
    - 100%
  order: sorted
  tasks:
    - name: task 1 sleep for 0.5 second
      command: sleep 0.5
      changed_when: false

    - name: task 2 sleep for 0.5 second
      command: sleep 0.5
      changed_when: false
...
